### ISSUE TITLE
TypeError: string indices must be integers for artist "Various artists"

### ISSUE THREAD

**Issue by alim4r** [krateng/maloja#111]
It seems that scrobbles with artist `Various artists` throw following error:

### main page
```python
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 278, in mainpage
    return jinja_page("start")
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 258, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 1, in top-level template code
    {% extends "abstracts/base.jinja" %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/abstracts/base.jinja", line 27, in top-level template code
    {% block content %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 34, in block 'content'
    {% include 'partials/charts_artists_tiles.jinja' %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/partials/charts_artists_tiles.jinja", line 25, in top-level template code
    <a href="{{ links.url(artist) }}">
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/snippets/links.jinja", line 21, in template
    {{ mlj_uri.create_uri("/track",{'track':entity}) }}
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 66, in create_uri
    return path + "?" + uriencode(*keydicts)
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 73, in uriencode
    return compose_querystring(internal_to_uri(keyd))
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 84, in internal_to_uri
    for a in keys["track"]["artists"]:
TypeError: string indices must be integers
```

### https://{domain}/artist?artist=Various+artists (only if an entry exists)
```python
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 273, in jinja_page_public
    return jinja_page(name)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 258, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/artist.jinja", line 27, in top-level template code
    {% set encodedartist = mlj_uri.uriencode({'artist':artist}) %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/abstracts/base.jinja", line 27, in top-level template code
    {% block content %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/artist.jinja", line 79, in block 'content'
    {% include 'partials/charts_tracks.jinja' %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/partials/charts_tracks.jinja", line 48, in top-level template code
    {{ entityrow.row(e['track']) }}
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/snippets/entityrow.jinja", line 17, in template
    <span class='artist_in_trackcolumn'>{{ links.links(entity.artists) }}</span> – {{ links.link(entity) }}
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/snippets/links.jinja", line 13, in template
    {{ link(entity) }}{{ ", " if not loop.last }}
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/snippets/links.jinja", line 8, in template
    <a href="{{ url(entity) }}">{{ name }}</a>
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/snippets/links.jinja", line 21, in template
    {{ mlj_uri.create_uri("/track",{'track':entity}) }}
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 66, in create_uri
    return path + "?" + uriencode(*keydicts)
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 73, in uriencode
    return compose_querystring(internal_to_uri(keyd))
  File "/usr/lib/python3.9/site-packages/maloja/malojauri.py", line 84, in internal_to_uri
    for a in keys["track"]["artists"]:
TypeError: string indices must be integers
```

## Workaround
Delete entry of scrobble in scrobbles table with `sqlite3` cli tool:

### find timestamp
```sh
sqlite> SELECT * FROM scrobbles;

# Example entries that throw the error
1649793575|{"track_artists": ["Various artists"], "track_title": "Train", "scrobble_time": 1649793575}|client:PC||2271|{}
1649924354|{"track_artists": ["Various artists"], "track_title": "Free Yourself (feat. Raff)", "scrobble_time": 1649924354}|client:PC||2435|{}
```

### delete entry
```sh
sqlite> DELETE FROM scrobbles WHERE timestamp = 1649924354 ;
```

(also maybe a restart was needed after the deletion )

## Info
Version: 3.0.1
Docker arm/v7

**Comment by krateng** [comment]
If you're running from source, can you test it with the latest commit? If not, I'll push the next version in a bit, pretty sure it should be fixed.

**Comment by alim4r** [comment]
Thanks, that was fast! I really like your project.

Just started a docker build in the gitlab-ci which takes about 45 min (because it has to build some of the requirements for arm).
I get back to you later today.

**Comment by alim4r** [comment]
@krateng Just checked, it works!
