### ISSUE TITLE
Cannot import last.fm scrobbles

### ISSUE THREAD

**Issue by ICTman1076** [krateng/maloja#115]
It seems between 2.14.10 and 3.0.0 last.fm scrobble importing broke.

This is logging output for just trying a bog standard import:

```
Parsing ICTman1076.csv as Last.fm export
This could take a while...
Imported 1000 scrobbles...
Traceback (most recent call last):
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: trackartists.artist_id, trackartists.track_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/home/ictman/.local/lib/python3.9/site-packages/doreah/control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maloja/proccontrol/control.py", line 140, in main
    return action(*args,**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maloja/proccontrol/tasks/import_scrobbles.py", line 96, in import_scrobbles
    add_scrobbles(scrobblebuffer)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 118, in wrapper
    return func(*args,**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 250, in add_scrobbles
    ops = [
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 252, in <listcomp>
    **scrobble_dict_to_db(s)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 216, in scrobble_dict_to_db
    "track_id":get_track_id(info['track']),
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/dbcache.py", line 56, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 118, in wrapper
    return func(*args,**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/sqldb.py", line 325, in get_track_id
    result = dbconn.execute(op)
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ictman/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: trackartists.artist_id, trackartists.track_id
[SQL: INSERT INTO trackartists (artist_id, track_id) VALUES (?, ?)]
[parameters: (300, 556)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[dbcache] Cache Size: 215 [0 E], System RAM Utilization: 2.6%, Cache Hits: 143/359
[sqldb] Database Cleanup...
[sqldb] Deleting (1, 226, 418)
[sqldb] Deleting (2, 227, 419)
[sqldb] Deleting (3, 227, 420)
... more numbers ...
[sqldb] Deleting (165, 300, 556)
[sqldb] Deleting (418, 'Nova', 'nova', None)
[sqldb] Deleting (419, 'Time', 'time', None)
... more songs ...
[sqldb] Deleting (556, 'We Are Young', 'we are young', None)
[sqldb] Deleting (226, 'Ahrix', 'ahrix')
[sqldb] Deleting (227, 'Swedish House Mafia', 'swedish house mafia')
... more artists ...
[sqldb] Deleting (300, 'Janelle Monae', 'janelle monae')
[sqldb] Database Cleanup complete!
```

I then tried to downgrade to 2.14.10, import (which worked), upgrade and then export, but on starting the upgraded server I get:

```
[upgrade] Upgrading v2 Database to v3 Database. This could take a while...
[upgrade]       Importing from lastfmimport.tsv (1/1) - 6713 Scrobbles
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maloja/database/__init__.py", line 386, in start_db
    upgrade.upgrade_db(sqldb.add_scrobbles)
  File "/usr/local/lib/python3.9/dist-packages/maloja/upgrade.py", line 70, in upgrade_db
    timestamp, artists, title, album, duration = scrobble
ValueError: not enough values to unpack (expected 5, got 4)
```

This is running on an ARM server at Oracle.

**Comment by krateng** [comment]
The below error should be fixed in the latest version (3.0.3). As for the initial error, are you importing data that is partially already in your database?

**Comment by ICTman1076** [comment]
> As for the initial error, are you importing data that is partially already in your database?

It's a brand new installation. My last.fm is `ICTman1076` if you want the data.

>The below error should be fixed in the latest version (3.0.3)

Ok, thanks, I'll use that as a workaround :)

**Comment by krateng** [comment]
Thanks for the data! I think I've found the issue... might take some time.

**Comment by ICTman1076** [comment]
> The below error should be fixed in the latest version (3.0.3)

That particular error looks fixed, but then it runs straight back into the error with a standard lastfm import. Glad to hear you think you've found the problem, I'll look forward to a fix :)

**Comment by krateng** [comment]
Alright, I tested it with your data and it works in the latest commit if you're building from source. Otherwise, I'll push the next version very soon.

**Comment by ICTman1076** [comment]
Thank you :)
