### ISSUE TITLE
Package from PyPi not working

### ISSUE THREAD

**Issue by temrix** [krateng/maloja#12]
If the package is installed on `amd64` only by typing `pip3 install malojaserver`, which is the recommended way in the docs and `install_alpine.sh` and `install_ubuntu.sh` do not say otherwise, I get a traceback:

```
$ maloja run
Traceback (most recent call last):
  File "/home/temrix/Downloads/maloja/venv/bin/maloja", line 10, in <module>
    sys.exit(main())
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/doreah/control.py", line 44, in wrapper
    return func(*args,**kwargs)
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/controller.py", line 195, in main
    if action in actions: actions[action](*args,**kwargs)
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/controller.py", line 169, in direct
    from . import server
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/server.py", line 12, in <module>
    from . import database
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/database.py", line 4, in <module>
    from .cleanup import CleanerAgent, CollectorAgent
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/cleanup.py", line 2, in <module>
    from . import utilities
  File "/home/temrix/Downloads/maloja/venv/lib/python3.7/site-packages/maloja/utilities.py", line 150, in <module>
    cacheage = settings.get_settings("CACHE_EXPIRE_POSITIVE") * 24 * 3600
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

However, on armhf, using this method, it is installing just fine. I noticed `pkg-resources==0.0.0` as an additional package being installed on `amd64`.

**Comment by krateng** [comment]
`maloja run` doesn't work without an initial setup yet, see GH-10. The intended way to start the server is with `maloja start`.

**Comment by temrix** [comment]
Ah, I see. Thank you!
