### ISSUE TITLE
Spotify import: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by northys** [krateng/maloja#124]
I've started maloja on my laptop with datafolder mounted from laptop's /tmp. I wanted to try to import spotify's streaming history but it doesn't work while I have no issues importing my last.fm history from the csv in the same directory.

```
/mljdata # cat StreamingHistory0.json | wc -l
60001


/mljdata # maloja import StreamingHistory0.json 
Parsing StreamingHistory0.json as Spotify export
This could take a while...
Traceback (most recent call last):
  File "/usr/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/doreah/control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/control.py", line 140, in main
    return action(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/tasks/import_scrobbles.py", line 63, in import_scrobbles
    for status,scrobble,msg in importfunc(inputf):
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/tasks/import_scrobbles.py", line 122, in parse_spotify_lite
    inputfiles = [os.path.join(inputfolder,f) for f in os.listdir(inputfolder) if filenames.match(f)]
FileNotFoundError: [Errno 2] No such file or directory: ''


/mljdata # head StreamingHistory0.json 
[
  {
    "endTime" : "2021-04-19 19:24",
    "artistName" : "Shinedown",
    "trackName" : "45",
    "msPlayed" : 205536
  },
  {
    "endTime" : "2021-04-21 02:19",
    "artistName" : "Def Leppard",

```

**Comment by krateng** [comment]
Ah, I see the problem. Gonna fix it, but you should just be able to run `maloja import ./StreamingHistory.json` as a quick workaround.
