### ISSUE TITLE
Error when browsing past years

### ISSUE THREAD

**Issue by northys** [krateng/maloja#126]
I have successfully imported my last.fm. Thanks for the time fix.

When I open scrobbles page for year (/scrobbles?in=2013) it fails for some of them. I can open most of years but 2 of them produce 500 server error.

Logs produced
```
[thirdparty] Got track image for (['The Agonist'], 'Remnants in Time') from Deezer
[thirdparty] Could not get track image for (['Deathbeds AU'], 'A Night in Hell') from Deezer
[server] Waitress Task Queue Depth at 13
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 275, in jinja_page_public
    return jinja_page(name)
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/profiler.py", line 28, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 260, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/scrobbles.jinja", line 7, in top-level template code
    {% set scrobbles = dbc.get_scrobbles(filterkeys,limitkeys,amountkeys) %}
  File "/usr/lib/python3.9/site-packages/maloja/database/jinjaview.py", line 42, in packedmethod
    result = originalmethod(**kwargs,dbconn=self.conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 62, in newfunc
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 164, in get_scrobbles
    result = sqldb.get_scrobbles(since=since,to=to,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 56, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 114, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 420, in get_scrobbles
    result = scrobbles_db_to_dict(result)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 161, in scrobbles_db_to_dict
    tracks = get_tracks_map(set(row.track_id for row in rows))
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 88, in outer_func
    remaining = inner_func(set(e for e in set_arg if e not in result),dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 118, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 604, in get_tracks_map
    trackdicts = tracks_db_to_dict(result)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 184, in tracks_db_to_dict
    return [
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 186, in <listcomp>
    "artists":artists[row.id],
KeyError: 22761

```

**Comment by northys** [comment]
I got similar error after importing spotify export. It got fixed by reseting cache by restarting the docker container though...

The error in original post did not get fixed by restarting the container though :(

```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 280, in mainpage
    return jinja_page("start")
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/profiler.py", line 28, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 260, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 1, in top-level template code
    {% extends "abstracts/base.jinja" %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/abstracts/base.jinja", line 30, in top-level template code
    {% block content %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 58, in block 'content'
    {% include 'partials/charts_tracks_tiles.jinja' %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/partials/charts_tracks_tiles.jinja", line 5, in top-level template code
    {% set charts = dbc.get_charts_tracks(filterkeys,limitkeys) %}
  File "/usr/lib/python3.9/site-packages/maloja/database/jinjaview.py", line 42, in packedmethod
    result = originalmethod(**kwargs,dbconn=self.conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 62, in newfunc
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 206, in get_charts_tracks
    result = sqldb.count_scrobbles_by_track(since=since,to=to,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 56, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 114, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 541, in count_scrobbles_by_track
    result = [{'scrobbles':row.count,'track':tracks[row.track_id]} for row in result]
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 541, in <listcomp>
    result = [{'scrobbles':row.count,'track':tracks[row.track_id]} for row in result]
KeyError: 37242
```

**Comment by krateng** [comment]
Hm, could still be a cache issue - could you try with your cache disabled? (Change the setting, then restart)

**Comment by krateng** [comment]
Thinking about it, this could also simply be a case of something being deleted by the main process database cleanup while the import process was writing to it. You might have to redo your imports if disabling the cache doesn't do anything.

**Comment by northys** [comment]
I will try to import it again when maloja is stopped. If it helps I'll add a note to readme.
