### ISSUE TITLE
Issue with 3.1.1 (3.1.0 works fine) config file changes perhaps?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#142]
I've checked the changelogs and can see maybe a config change in 3.1.1, but cannot see if there are any changes to the config file needed?

```
Traceback (most recent call last):
File "/usr/bin/maloja", line 5, in <module>
from maloja.__main__ import main
File "/usr/lib/python3.9/site-packages/maloja/__init__.py", line 4, in <module>
from .pkg_global import conf
File "/usr/lib/python3.9/site-packages/maloja/pkg_global/conf.py", line 128, in <module>
malojaconfig = Configuration(
File "/usr/lib/python3.9/site-packages/doreah/configuration.py", line 38, in __init__
self.usersettings = DiskDict(filename=configfile)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 23, in __init__
self._sync_to_disk()
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 36, in _sync_to_disk
self.handler.write_file(tmpfile,data)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 91, in write_file
return self.write_descriptor(descriptor,data)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 162, in write_descriptor
cfg['MALOJA'] = data
File "/usr/lib/python3.9/configparser.py", line 977, in __setitem__
self.read_dict({key: value})
File "/usr/lib/python3.9/configparser.py", line 754, in read_dict
self.set(section, key, value)
File "/usr/lib/python3.9/configparser.py", line 1203, in set
self._validate_value_types(option=option, value=value)
File "/usr/lib/python3.9/configparser.py", line 1188, in _validate_value_types
raise TypeError("option values must be strings")
TypeError: option values must be strings
Traceback (most recent call last):
File "/usr/bin/maloja", line 5, in <module>
from maloja.__main__ import main
File "/usr/lib/python3.9/site-packages/maloja/__init__.py", line 4, in <module>
from .pkg_global import conf
File "/usr/lib/python3.9/site-packages/maloja/pkg_global/conf.py", line 128, in <module>
malojaconfig = Configuration(
File "/usr/lib/python3.9/site-packages/doreah/configuration.py", line 38, in __init__
self.usersettings = DiskDict(filename=configfile)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 23, in __init__
self._sync_to_disk()
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 36, in _sync_to_disk
self.handler.write_file(tmpfile,data)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 91, in write_file
return self.write_descriptor(descriptor,data)
File "/usr/lib/python3.9/site-packages/doreah/persistence.py", line 162, in write_descriptor
cfg['MALOJA'] = data
File "/usr/lib/python3.9/configparser.py", line 977, in __setitem__
self.read_dict({key: value})
File "/usr/lib/python3.9/configparser.py", line 754, in read_dict
self.set(section, key, value)
File "/usr/lib/python3.9/configparser.py", line 1203, in set
self._validate_value_types(option=option, value=value)
File "/usr/lib/python3.9/configparser.py", line 1188, in _validate_value_types
raise TypeError("option values must be strings")
TypeError: option values must be strings
```

**Comment by mannp** [comment]
> Thanks! Should be fixed with a doreah update, I'll also push the next version in a bit!

Cool, thanks for the prompt fix and update release :)
