### ISSUE TITLE
Error when importing Spotify listening export

### ISSUE THREAD

**Issue by saltwotter** [krateng/maloja#145]
Used the following command to initiate an import of the Spotify export files that I recently got:

```bash
maloja import StreamingHistory0.json
```

And after a while, it throws a RecursionError, saying that it reached Python's recursion depth limit, and then it hangs (requiring a Ctrl-C to get out). The tracks are also not logged.

Full output:

```bash
/mlj_config # maloja import StreamingHistory0.json 
[spotify] Successfully authenticated with Spotify
Parsing StreamingHistory0.json as Spotify export
This could take a while...
Spotify files should all be imported together to identify duplicates across the whole dataset.
Import ./StreamingHistory0.json, ./StreamingHistory2.json, ./StreamingHistory1.json? [Y/n]
n
Importing StreamingHistory0.json ...
Imported 1000 scrobbles...
[sqldb] 1000 Scrobbles have not been written to database!
[sqldb] Database Cleanup...
[dbcache] Cache: Size: 227 | Hits: 913/1140 | Estimated Memory: 6 KiB
[dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] System RAM Utilization: 38.3%[sqldb] Database Cleanup complete!

Imported 2000 scrobbles...
[sqldb] 1000 Scrobbles have not been written to database!
Imported 3000 scrobbles...
[sqldb] 1000 Scrobbles have not been written to database!
Imported 4000 scrobbles...
[sqldb] 1000 Scrobbles have not been written to database!
Traceback (most recent call last):
  File "/usr/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/doreah/control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/__main__.py", line 178, in main
    return action(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/tasks/import_scrobbles.py", line 74, in import_scrobbles
    (scrobble['track_artists'],scrobble['track_title']) = c.fullclean(scrobble['track_artists'],scrobble['track_title'])
  File "/usr/lib/python3.9/site-packages/maloja/cleanup.py", line 42, in fullclean
    (title,moreartists) = self.parseTitleForArtists(title)
  File "/usr/lib/python3.9/site-packages/maloja/cleanup.py", line 162, in parseTitleForArtists
    (title,artists) = self.parseTitleForArtists(re.sub(r"(.*) [\(\[]" + d + " (.*?)[\)\]]",r"\1",t,re.IGNORECASE))
  File "/usr/lib/python3.9/site-packages/maloja/cleanup.py", line 162, in parseTitleForArtists
    (title,artists) = self.parseTitleForArtists(re.sub(r"(.*) [\(\[]" + d + " (.*?)[\)\]]",r"\1",t,re.IGNORECASE))
  File "/usr/lib/python3.9/site-packages/maloja/cleanup.py", line 162, in parseTitleForArtists
    (title,artists) = self.parseTitleForArtists(re.sub(r"(.*) [\(\[]" + d + " (.*?)[\)\]]",r"\1",t,re.IGNORECASE))
  [Previous line repeated 988 more times]
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.9/re.py", line 291, in _compile
    if isinstance(flags, RegexFlag):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

If it helps, I recently upgraded from the last 2.x version to 3.1.2.

**Comment by krateng** [comment]
Would you mind sharing your `StreamingHistory0.json`?

**Comment by krateng** [comment]
Ah nevermind, reproduced it... working on it!

**Comment by krateng** [comment]
Should be fixed!
