### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by nothing2obvi** [krateng/maloja#147]
Hello, I'm a long-time user of Maloja. For some reason, using this new Docker image, I can't seem to login. The interface loads and everything, but after I enter the password and click on "Login," nothing happens.

**Comment by krateng** [comment]
Can you open the dev console in the browser and check what it says when you load the login page and when you press the login button?

**Comment by krateng** [comment]
Could you list the content of your `/config/auth/` folder?

**Comment by Spoons** [comment]
Something is wrong with the default app or container configuration. On a new install, `MALOJA_FORCE_PASSWORD` was set in the environment; there are no other configuration changes.
```
[server] Starting up Maloja server...
[server] Listening on *:42010
[dbcache] Cache: Size: 1 | Hits: 0/1 | Estimated Memory: 128 B
[dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] System RAM Utilization: 79.5%
[dbcache] 79.5% RAM usage, clearing cache!
[dbcache] Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] System RAM Utilization: 79.5%
[sqldb] Database Cleanup...
[sqldb] Database Cleanup complete!
[debug_performance] Executed jinja_page (('start',), {}) in 0.12s
Invalid response
Invalid response
Invalid response
Invalid response
Invalid response
Invalid response
Invalid response
Invalid response
Invalid response
```
![Screenshot_2022-07-14_21-11-54](https://user-images.githubusercontent.com/549853/179133434-87fcc75b-4cd7-46a1-9b42-9fcecee73042.png)

**Comment by qlyoung** [comment]
I have this same problem and am willing to provide data for debugging purposes.

**Comment by badlandspray** [comment]
I've the same issue as well

```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 870, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1750, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/nimrodel/_api.py", line 160, in route
    result = self.handle(nodes,reqmethod,keys,headers)
  File "/usr/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
    return func(**querykeys,**pathkeys)
  File "/usr/lib/python3.9/site-packages/doreah/auth.py", line 172, in get_token
    if u.validate_challenge(challenge,response):
  File "/usr/lib/python3.9/site-packages/doreah/auth.py", line 109, in validate_challenge
    if combine(pub,challenge) == combine(response,COMMON):
  File "/usr/lib/python3.9/site-packages/doreah/auth.py", line 74, in combine
    a = int(a,16)
ValueError: invalid literal for int() with base 16: ''

```

**Comment by badlandspray** [comment]
@krateng Can you confirm if you are able to reproduce or you need any more information?

**Comment by krateng** [comment]
I can't reproduce this unfortunately.

Can you try using a password with only letters and digits, no spaces or special characters (if that's not already the case)? Also, if anyone affected would be willing to share their docker compose file that could be helpful.

**Comment by badlandspray** [comment]
Sorry, this was my mistake. I don't remember adding `force_password` in settings.ini file and I was trying to login with a different password.

**Comment by FoxxMD** [comment]
Also having trouble logging in to the admin overview page. I type in my password and hit login but the `autheticate` request never returns a response

![image](https://user-images.githubusercontent.com/4663766/189910293-9af8a9fe-db2e-44f9-8829-a6380aebfc73.png)

There are no errors in the logs I can find.

**Comment by qlyoung** [comment]
Strangely, restarting mine worked also, even though I've tried it many times in the past.

**Comment by dahdanh** [comment]
I thought I had this issue too, but I realized I'm just goofy.

For anyone using a password manager that autofills, make sure you disable that. BitWarden will automatically fill the force-password field in the admin settings, and the settings save when you leave the page. So in my case, an incorrect password was filled in and I was not aware. Woops.

**Comment by swishkin** [comment]
I've been running Maloja without issues for about a year now, but suddenly I seem to be encountering the same as others experienced here a year or two ago. For reference, here's my anonymized docker-compose.yml:

```
version: "3"

services:
  maloja:
    container_name: "maloja"
    image: "krateng/maloja"
    env_file:
      stack.env
    ports:
    - "19180:42010"
    volumes:
    - "${MALOJA_DATA_DIR}:/data"
    restart: unless-stopped
networks:
  default:
    name: npm_default
    external: true
```

(different host-side port `19180` specified to avoid conflicts with other containers, and `npm_default` is the network I add my containers to in order to allow referring to them by hostname in Nginx Proxy Manager)

And stack.env (this is being deployed through Portainer):

```
MALOJA_FORCE_PASSWORD=</REDACTED/>
MALOJA_DATA_DIRECTORY=/data
MALOJA_SKIP_SETUP=true
MALOJA_TIMEZONE=-5
```

Originally, the password was in a similar format to this example password generated by Bitwarden: `Voicing1-Dipper-Drivable`. Based on a suggestion either in this issue or another, I cut it down to `Voicing1` (still an example), but the issue persisted.

Whenever I attempt login to `/admin_overview`, the browser console shows this output:

![image](https://github.com/user-attachments/assets/56859cef-995c-41fd-8459-7012faf30c3f)

I thought this might be a time-related issue for a bit, as daylight savings time in the US (somewhat) recently began, but altering the UTC offset from -6 (CST) to -5 (CDT) had no impact.

The same error occurs regardless of whether Maloja is accessed via FQDN or IP address, HTTP or HTTPS.

Out of a further idea relating to time zones, I ran `date` on the host and within the container, yeilding these results:

Host: `Wed Dec  4 11:59:17 AM CST 2024`
Container: `Wed Dec  4 17:59:27 UTC 2024`

(these commands were run *after* the container's UTC offset was changed from -6 to -5)

I'm not sure what's going on here. Is there any other information I can provide to assist in debugging this?

Thanks.

**Comment by swishkin** [comment]
This may not be the solution for anybody else, but for me, I simply had to add these two environment variables, and then i was able to log into Maloja again.
 
(The user ID should match the host user ID that owns the directory that Maloja is using, and the same should be true of the group ID)

```
PUID=1000
PGID=1000
```
