### ISSUE TITLE
Issues with installing maloja

### ISSUE THREAD

**Issue by kinescou** [krateng/maloja#148]
I've tried to install maloja using pip but I keep getting this error when I try to start the service.

```
Traceback (most recent call last):
  File "/home/kine/.local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/home/kine/.local/lib/python3.8/site-packages/doreah/control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "/home/kine/.local/lib/python3.8/site-packages/maloja/__main__.py", line 178, in main
    return action(*args,**kwargs)
  File "/home/kine/.local/lib/python3.8/site-packages/maloja/__main__.py", line 54, in start
    setup()
  File "/home/kine/.local/lib/python3.8/site-packages/maloja/setup.py", line 35, in setup
    copy_initial_local_files()
  File "/home/kine/.local/lib/python3.8/site-packages/maloja/setup.py", line 24, in copy_initial_local_files
    with resources.files("maloja") / 'data_files' as folder:
AttributeError: module 'importlib.resources' has no attribute 'files'
```

I'd really appreciate any help.

**Comment by krateng** [comment]
Ah, looks like that function doesn't exist in older Python versions - I'll see if I can implement a fallback, but for a quick fix, if you can upgrade to Python 3.9 or later, it should work.

**Comment by kinescou** [comment]
Thanks, worked great.

**Comment by TeaWhyDee** [comment]
maybe add python 3.9 requirement to readme?
