### ISSUE TITLE
TemplateNotFound(template)

### ISSUE THREAD

**Issue by northys** [krateng/maloja#150]
I just discovered this error in my logs. I did not change anything relating to templates, any idea, please?

```
2022-05-25T22:52:10.385231824Z [thirdparty] Got track image for (['Block McCloud', 'Kool G Rap', 'Vinnie Paz'], 'Wolves Amongst the Sheep') from MusicBrainz
2022-05-25T22:52:12.290796294Z [images] Downloaded https://coverartarchive.org/release/fbc4840d-cd23-484b-9b38-3423328c2bb5/25190784693.jpg for local caching
2022-05-25T22:58:56.638712573Z [debug_performance] Generated page with 0/0 local Cache hits
2022-05-25T22:58:56.642988649Z Traceback (most recent call last):
2022-05-25T22:58:56.643056022Z   File "/usr/bin/bottle.py", line 868, in _handle
2022-05-25T22:58:56.643074031Z     return route.call(**args)
2022-05-25T22:58:56.643086078Z   File "/usr/bin/bottle.py", line 1748, in wrapper
2022-05-25T22:58:56.643097031Z     rv = callback(*a, **ka)
2022-05-25T22:58:56.643107277Z   File "/usr/lib/python3.9/site-packages/maloja/server.py", line 233, in jinja_page_public
2022-05-25T22:58:56.643119262Z     return jinja_page(name)
2022-05-25T22:58:56.643129886Z   File "/usr/lib/python3.9/site-packages/maloja/dev/profiler.py", line 27, in newfunc
2022-05-25T22:58:56.643141374Z     result = func(*args,**kwargs)
2022-05-25T22:58:56.643153232Z   File "/usr/lib/python3.9/site-packages/maloja/server.py", line 216, in jinja_page
2022-05-25T22:58:56.643163749Z     template = jinja_environment.get_template(name + '.jinja')
2022-05-25T22:58:56.643173786Z   File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
2022-05-25T22:58:56.643184137Z     return self._load_template(name, globals)
2022-05-25T22:58:56.643194153Z   File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
2022-05-25T22:58:56.643204462Z     template = self.loader.load(self, name, self.make_globals(globals))
2022-05-25T22:58:56.643215027Z   File "/usr/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
2022-05-25T22:58:56.643225267Z     source, filename, uptodate = self.get_source(environment, name)
2022-05-25T22:58:56.643235384Z   File "/usr/lib/python3.9/site-packages/jinja2/loaders.py", line 344, in get_source
2022-05-25T22:58:56.643246184Z     raise TemplateNotFound(template)
2022-05-25T22:58:56.643289124Z jinja2.exceptions.TemplateNotFound: apis.jinja
2022-05-25T22:58:57.718654340Z [debug_performance] Generated page with 0/20 local Cache hits
2022-05-25T22:58:57.721704966Z [debug_performance] Executed jinja_page (('start',), {}) in 1.05s
2022-05-25T23:00:06.427228683Z [sqldb] Database Cleanup...
2022-05-25T23:00:08.508586334Z [sqldb] Database Cleanup complete!
2022-05-25T23:00:16.346427308Z [dbcache] Cache: Size: 1361 | Hits: 321/1682 | Estimated Memory: 261 MiB
2022-05-25T23:00:17.657611523Z [dbcache] Entity Cache: Size: 85913 | Hits: 79879/165792 | Estimated Memory: 17 MiB
2022-05-25T23:00:17.658482517Z [dbcache] System RAM Utilization: 34.5%
```

**Comment by krateng** [comment]
This simply means someone has tried to access `yoururl.tld/apis`, which is not a valid page, but shouldn't inherently be a problem. If you haven't accessed that page and your instance isn't public, you could have a misconfigured client - but you'd notice missing scrobbles / error feedback from the client.

**Comment by northys** [comment]
Yeah, I loaded server info page. I would expect that this issue would be caught or something in case of API calls. Is there an api endpoint which needs templates?

**Comment by krateng** [comment]
In the current structure `/api` itself, funnily enough, doesn't actually count as an API call yet, that's why it's treated as a website. I'll have a look if I can change that.
