### ISSUE TITLE
Error when importing v2 data

### ISSUE THREAD

**Issue by joldeski** [krateng/maloja#164]
Hey there, I've been on an old version of Maloja for a while. I've upgraded, and am getting this error when running Maloja from docker-compose.

```yaml
maloja             |
maloja             | Maloja v3.1.3
maloja             | https://github.com/krateng/maloja
maloja             |
maloja             | Various external services can be used to display images. If not enough of them are set up, only local images will be used.
maloja             | 	Last.fm API Key found.
maloja             | 	Spotify API ID found.
maloja             | 	Spotify API Secret found.
maloja             | 	Currently not using a TheAudioDB API Key for image display.
maloja             | Your API Key: <redacted>
maloja             | Password has been set.
maloja             | [server] Starting up Maloja server...
maloja             | [server] Listening on 0.0.0.0:42010
maloja             | [upgrade] Upgrading v2 Database to v3 Database. This could take a while...
maloja             | [upgrade] 	Importing from lastfmimport.tsv (1/5) - 46133 Scrobbles
maloja             | Exception in thread Thread-10:
maloja             | Traceback (most recent call last):
maloja             |   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
maloja             |     self.run()
maloja             |   File "/usr/lib/python3.9/threading.py", line 910, in run
maloja             |     self._target(*self._args, **self._kwargs)
maloja             |   File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 466, in start_db
maloja             |     upgrade.upgrade_db(sqldb.add_scrobbles)
maloja             |   File "/usr/lib/python3.9/site-packages/maloja/upgrade.py", line 70, in upgrade_db
maloja             |     timestamp, artists, title, album, duration, *_ = scrobble + [None,None]
maloja             | ValueError: not enough values to unpack (expected at least 5, got 3)
maloja             | [dbcache] Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
maloja             | [dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
maloja             | [dbcache] System RAM Utilization: 28.0%
maloja             | [sqldb] Database Cleanup...
maloja             | [sqldb] Database Cleanup complete!
```
The web interface is giving a 503, with the message "The Maloja Database is being upgraded to Version 3. This could take quite a long time! (~ 2-5 minutes per 10 000 scrobbles)".
After waiting about an hour, it didn't change. The db file remained the same size.
Any ideas?

**Comment by krateng** [comment]
Would you mind sharing your `lastfrmimport.tsv` file?

**Comment by joldeski** [comment]
Hey, I managed to import the data by manually opening the file and adding the last column that didn't exist (the duration column).

I used Excel to open the TSV, subtracted the difference between both timestamps, removed any duration values greater than 999, and re-added it to the scrobbles folder.

Unfortunately, now there aren't any images being rendered on the web interface. I'm not really sure how to get Maloja to generate them (I've given it API keys for lastfm and spotify)

**Comment by joldeski** [comment]
Here's the error message:

```
maloja             | Traceback (most recent call last):
maloja             |   File "/usr/bin/bottle.py", line 868, in _handle
maloja             |     return route.call(**args)
maloja             |   File "/usr/bin/bottle.py", line 1748, in wrapper
maloja             |     rv = callback(*a, **ka)
maloja             |   File "/usr/lib/python3.9/site-packages/maloja/server.py", line 122, in dynamic_image
maloja             |     if keys['type'] == 'track':
maloja             |   File "/usr/bin/bottle.py", line 1834, in __getitem__
maloja             |     def __getitem__(self, key): return self.dict[key][-1]
maloja             | KeyError: 'type'
```

**Comment by krateng** [comment]
Last.fm needs an API Key as well as an API secret, Spotify needs an API ID and an API Secret. Did you add all those?

**Comment by joldeski** [comment]
yup! they're added.

**Comment by krateng** [comment]
From the error message I can only guess a caching issue right now. Could you clear all caches, refresh the front page and see if any images show up?

**Comment by joldeski** [comment]
The URL being called is `https://maloja.mydomain.com/image?type=track&id=4495`, which responds with a blank page but gives a 200 response.

Anyway, seeing as I solved my original issue, and my not having the spare time to debug this further at the moment, I'm closing this issue.

Thanks for developing this software, it's been very useful! I really appreciate it.
