### ISSUE TITLE
Installed via PIP - Issues with Python 3?

### ISSUE THREAD

**Issue by ajaxStardust** [krateng/maloja#180]
Any idea what I'm doing wrong? I rarely mess w/ pip / python apps like this, but i don't expect i'd encounter much difficulty in solving my problem w/ a bit of guidance. 

`maloja start
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PS C:\Users\jsaba> maloja run
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PS C:\Users\jsaba> maloja restart
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by ajaxStardust** [comment]
maloja start
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PS C:\Users\jsaba> maloja run
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
PS C:\Users\jsaba> maloja restart
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Python310\lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Python310\lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "C:\Python310\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by bulletproof2k** [comment]
![photo_2023-01-24_19-18-17](https://user-images.githubusercontent.com/1818579/214815223-ed639efa-1e8e-4066-91d3-25b51ed80ac0.jpg)

**Comment by krateng** [comment]
Sorry, I can't offer any help with Windows issues - looks like it has something to do with filepaths. Maloja might just be plain incompatible with Windows.
