### ISSUE TITLE
Error 500 when accessing admin_issues

### ISSUE THREAD

**Issue by KucharczykL** [krateng/maloja#189]
When going to the `/admin_issues` URL (for example from https://github.com/krateng/maloja/blob/master/maloja/web/jinja/admin_setup.jinja#L93), I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/doreah/auth.py", line 238, in newfunc
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 231, in jinja_page_private
    return jinja_page(name)
  File "/usr/lib/python3.9/site-packages/maloja/dev/profiler.py", line 27, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 218, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/admin_issues.jinja", line 36, in top-level template code
    {% set issuedata = dbc.issues() %}
  File "/usr/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'maloja.database.jinjaview.JinjaDBConnection object' has no attribute 'issues'
```

**Comment by bbsixzz** [comment]
Same, using the latest docker image.

**Comment by krateng** [comment]
Sorry, looks like that is a link I left in by accident - issues haven't been reimplemented for the new database system. I'll remove the reference.
