### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by domainzero** [krateng/maloja#196]
Not sure when it started happening, recently my maloja instance has been erroring out.
I enabled logging, but it doesn't show anything particularly useful.  
  
I logged in to admin mode and got this message on the main page.
I'm thinking this maybe has something to do with my top artists, but am not sure.

```python
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/maloja/database/dbcache.py", line 47, in outer_func
    return cache[key]
KeyError: ('["The Armed"]', '{}', <function connection_provider.<locals>.wrapper at 0x7fe6d8d08430>, None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/home/user/.local/lib/python3.10/site-packages/bottle.py", line 1756, in wrapper
    rv = callback(*a, **ka)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/server.py", line 240, in mainpage
    return jinja_page("start")
  File "/home/user/.local/lib/python3.10/site-packages/maloja/dev/profiler.py", line 27, in newfunc
    result = func(*args,**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/server.py", line 218, in jinja_page
    res = template.render(**loc_context)
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/user/.local/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/web/jinja/start.jinja", line 1, in top-level template code
    {% extends "abstracts/base.jinja" %}
  File "/home/user/.local/lib/python3.10/site-packages/maloja/web/jinja/abstracts/base.jinja", line 34, in top-level template code
    {% block content %}
  File "/home/user/.local/lib/python3.10/site-packages/maloja/web/jinja/start.jinja", line 34, in block 'content'
    {% include 'partials/charts_artists_tiles.jinja' %}
  File "/home/user/.local/lib/python3.10/site-packages/maloja/web/jinja/partials/charts_artists_tiles.jinja", line 30, in top-level template code
    <div style='background-image:url("{{ images.get_artist_image(artist) }}")'>
  File "/home/user/.local/lib/python3.10/site-packages/maloja/images.py", line 114, in get_artist_image
    artist_id = database.sqldb.get_artist_id(artist)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/database/dbcache.py", line 49, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/database/sqldb.py", line 120, in wrapper
    return func(*args,**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/maloja/database/sqldb.py", line 346, in get_artist_id
    op = DB['artists'].select(
TypeError: FromClause.select() takes 1 positional argument but 2 were given
```

**Comment by krateng** [comment]
Which pages are generating the error? Is it consistent for the same pages, or does it happen randomly? And after a restart / wipe, does it immediately happen again or pop up after a while?

**Comment by domainzero** [comment]
I don't get the error with an empty database (i.e. I move my current database and restart maloja). I see a  `500 Internal Server` error on any page besides the admin page, so it leads me to believe that it's definitely something with parsing scrobbles or artists or something.

**Comment by krateng** [comment]
Alright I pushed a small fix that might avoid the issue if my suspicion is correct. Let me know if you can test it from source, but I'll probably push a new version soon anyway.

**Comment by domainzero** [comment]
> Looks like that fixed it for me +1

Same. Thanks!
