### ISSUE TITLE
Any way to change first day of the week?

### ISSUE THREAD

**Issue by janaxhell** [krateng/maloja#216]
Looks like the first day of the week is set to sunday, but in my country it's monday: any way to change this?

**Comment by SirMartin** [comment]
I want to know, if there is any plan of fixing this, make the first day of week as an option should be pretty simple.

**Comment by SirMartin** [comment]
I would try to make a PR with a contribution for it.

**Comment by krateng** [comment]
Should now be fixed, I'll just have to make sure if this doesn't cause any weirdness in unexpected places

**Comment by SirMartin** [comment]
I would try next time 🤣

**Comment by janaxhell** [comment]
> Should now be fixed, I'll just have to make sure if this doesn't cause any weirdness in unexpected places

After this update, something broke. Watchtower autoupdated the container, which now stops at start with an error:
```

???????????????????????????????????????
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 
  Based on images from linuxserver.io
???????????????????????????????????????
To support LSIO projects visit:
https://www.linuxserver.io/donate/
???????????????????????????????????????
GID/UID
???????????????????????????????????????
User UID:    998
User GID:    100
???????????????????????????????????????
[custom-init] No custom files found, skipping...
Maloja is starting!
[ls.io-init] done.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.10/site-packages/maloja/__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "/usr/lib/python3.10/site-packages/maloja/pkg_global/conf.py", line 334, in <module>
    from ..database.sqldb import set_maloja_info
  File "/usr/lib/python3.10/site-packages/maloja/database/__init__.py", line 22, in <module>
    from ..apis import apikeystore
  File "/usr/lib/python3.10/site-packages/maloja/apis/__init__.py", line 1, in <module>
    from ._apikeys import apikeystore
  File "/usr/lib/python3.10/site-packages/maloja/apis/_apikeys.py", line 12, in <module>
    from .. import upgrade
  File "/usr/lib/python3.10/site-packages/maloja/upgrade.py", line 14, in <module>
    from .database.sqldb import get_maloja_info, set_maloja_info
  File "/usr/lib/python3.10/site-packages/maloja/database/sqldb.py", line 123, in <module>
    meta.create_all(engine)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5828, in create_all
    bind._run_ddl_visitor(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3243, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2447, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 919, in visit_metadata
    self.traverse_single(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 957, in visit_table
    )._invoke_with(self.connection)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
CREATE TABLE _maloja (
	"key" VARCHAR NOT NULL, 
	value VARCHAR, 
	PRIMARY KEY ("key")
)
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/maloja/database/__init__.py", line 9, in wrapper
    from ..pkg_global import conf
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1405, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1242, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1238, in _get_parent_path
KeyError: 'maloja'
```

**Comment by janaxhell** [comment]
What do you mean by "improperly shutdown containers"? When I saw that maloja wasn't accessible, I checked the log, saw the error, restarted container and got again the same error. Before watchtower updated it, I hadn't touched maloja since I opened this issue, nor changed any folder permission.
