### ISSUE TITLE
TyperError after installation

### ISSUE THREAD

**Issue by Kaladania** [krateng/maloja#230]
After following the steps to install Maloja on a Window's machine, I recieve the following error message when attempting to start the server:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nicole\AppData\Local\Programs\Python\Python311\Scripts\maloja.exe\__main__.py", line 4, in <module>
  File "C:\Users\Nicole\AppData\Local\Programs\Python\Python311\Lib\site-packages\maloja\__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "C:\Users\Nicole\AppData\Local\Programs\Python\Python311\Lib\site-packages\maloja\pkg_global\conf.py", line 114, in <module>
    os.makedirs(maloja_dir_config,exist_ok=True)
  File "<frozen os>", line 210, in makedirs
  File "<frozen ntpath>", line 213, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by krateng** [comment]
I'm afraid I'm not sure Maloja can work on Windows at all, but maybe someone else is running it and can offer some input.

**Comment by Kaladania** [comment]
Okay, thank you. Do you know where the installation files would be located so that I can clear off the database in case I can't get it working?

**Comment by krateng** [comment]
You can try the command `maloja info` if that doesn't also throw an error. From some quick searching how it works on Windows, I think it could be something like `C:\Users\Nicole\.local\share\maloja`, but I can't say for sure.

**Comment by Kaladania** [comment]
Alright. Thanks for your help
