### ISSUE TITLE
Issue on Spotify's end causing history import to crash

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#232]
A couple of the listens in the history i received look like this:
```json
        "master_metadata_track_name": null,
        "master_metadata_album_artist_name": null,
        "master_metadata_album_album_name": null,
```
which causes this issue:
```py
Traceback (most recent call last):
  File "/usr/local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/doreah/control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "maloja/maloja/__main__.py", line 185, in main
    return action(*args,**kwargs)
  File "maloja/maloja/proccontrol/tasks/import_scrobbles.py", line 88, in import_scrobbles
    (scrobble['track_artists'],scrobble['track_title']) = c.fullclean(scrobble['track_artists'],scrobble['track_title'])
  File "maloja/maloja/cleanup.py", line 41, in fullclean
    artists = self.parseArtists(self.removespecial(artist))
  File "maloja/maloja/cleanup.py", line 64, in removespecial
    s = s.replace("\t","").replace("␟","").replace("\n","")
AttributeError: 'NoneType' object has no attribute 'replace'
```

This must be an issue on Spotify's end, including invalid listens. Perhaps these are tracks that have been removed from the platform. I suggest adding a check for the track name being equal to `null` and skipping it. I can try to do it myself and open a PR if needed.

**Comment by krateng** [comment]
Should be fixed!

**Comment by duckfromdiscord** [comment]
Perfect, thank you 🙂 working just fine now. Will let you know if anything else happens
