### ISSUE TITLE
Random issue when adding art to a song

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#239]
Some songs don't have images for one reason or another (generally because it's a Local File on Spotify) so I like to add them by drag-and-drop. Unfortunately every so often this seems to stop working until a full restart of Maloja.

Network tab shows a repeated POST to `https://[ip]:[port]/apis/mlj_1/addpicture?artist=[name of the artist]&title=[title of the song]`, resulting in code 500 and the response `{"status": "failure", "error": {"type": "unknown_error", "value": "AttributeError(\"'NoneType' object has no attribute 'split'\")", "desc": "The server has encountered an exception."}}` On maloja's end, here's the log:
```
[debug] Trying to set image, b64 string: data:image/png;base64,iVBORw0K...
[debug] Saved image as /var/lib/maloja/images/tracks/[name of the artist]_[title of the song]/webupload[some number].png
Traceback (most recent call last):
  File ".../maloja/maloja/apis/native_v1.py", line 97, in protector
    return func(*args,**kwargs)
  File ".../maloja/maloja/apis/native_v1.py", line 538, in add_picture
    url = images.set_image(b64,**k_filter)
  File .../maloja/maloja/images.py", line 441, in set_image
    set_image_in_cache(**idkeys,url=os.path.join("/images",folder,filename),local=True)
  File ".../maloja/maloja/images.py", line 99, in set_image_in_cache
    remove_image_from_cache(track_id=track_id,artist_id=artist_id,album_id=album_id)
  File ".../maloja/maloja/images.py", line 138, in remove_image_from_cache
    targetpath = data_dir['cache']('images',row.localproxyurl.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
```

After a double Control-C and a `maloja run`, dragging the same image into the same box results in two requests to maloja, same URL, but the first one returns a 308, probably because of the second request, and the second returns a 200. Both display a success and a link to the new image.

**Comment by duckfromdiscord** [comment]
I was able to fix the issue by wrapping the `remove_image_from_cache` with a try/except
