### ISSUE TITLE
Strange NoneType error at `/apis/mlj_1/charts/tracks`

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#243]
Working on #242, I also wanted to add a second function to the API: `get_charts_albums_external`, but I noticed that on my end, it and `/charts/tracks` don't work, but `/charts/artists` **DOES**. My guess is some track with a null name somewhere from one of the Spotify imports.

```py
Traceback (most recent call last):
  File ".../maloja/maloja/database/dbcache.py", line 48, in outer_func
    return cache[key]
KeyError: ('[]', '{"since": 1640726520, "to": 1694217599, "artist": null, "resolve_ids": true}', <function connection_provider.<locals>.wrapper at 0x...>, 1640726520, 1694217599)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../maloja/maloja/database/dbcache.py", line 48, in outer_func
    return cache[key]
KeyError: ('[null]', '{}', <function connection_provider.<locals>.wrapper at 0x...>, None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../maloja/maloja/apis/native_v1.py", line 97, in protector
    return func(*args,**kwargs)
  File ".../maloja/maloja/apis/native_v1.py", line 310, in get_charts_tracks_external
    result = database.get_charts_tracks(**ckeys)
  File ".../maloja/maloja/database/__init__.py", line 66, in newfunc
    return func(*args,**kwargs)
  File ".../maloja/maloja/database/__init__.py", line 377, in get_charts_tracks
    result = sqldb.count_scrobbles_by_track_of_artist(since=since,to=to,artist=keys['artist'],resolve_ids=resolve_ids,db
conn=dbconn)
  File ".../maloja/maloja/database/dbcache.py", line 50, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File ".../maloja/maloja/database/sqldb.py", line 157, in wrapper
    return func(*args,**kwargs)
  File ".../maloja/maloja/database/sqldb.py", line 1079, in count_scrobbles_by_track_of_artist
    artist_id = get_artist_id(artist,dbconn=dbconn)
  File ".../maloja/maloja/database/dbcache.py", line 50, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File ".../maloja/maloja/database/sqldb.py", line 152, in wrapper
    return func(*args,**kwargs)
  File ".../maloja/maloja/database/sqldb.py", line 462, in get_artist_id
    nname = normalize_name(artistname)
  File ".../maloja/maloja/database/sqldb.py", line 1680, in normalize_name
    name = name.replace(r," ")
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by duckfromdiscord** [comment]
Apparently the issue in next_minor_version occurs in the database code: [maloja/database/\_\_init\_\_.py#L376](https://github.com/krateng/maloja/blob/next_minor_version/maloja/database/__init__.py#L376). `'artist' in keys` passes, because it is there, it's just `None`. In other words, `('artist' in keys) == true` and `keys['artist'] == None`. The way I've fixed this is by making the line `if ('artist' in keys) and (keys['artist'] != None):` instead.
