### ISSUE TITLE
invalid_artist setting ends up in 500 Internal Server Error

### ISSUE THREAD

**Issue by weilah** [krateng/maloja#253]
hi there,

could someone please help me setting up correctly the invalid artist property in settings.ini?

I'm having troubles defining more than one artist with spaces and spacial chars in the name (like ä/ü/ö). I started with `invalid_artists = {'Name Surname', 'Näme Surname', 'Name Sürname'}` but I get a 500 Internal Server Error with every combination I try.

I can provide more logs if needed.
Thanks!

**Comment by krateng** [comment]
Can you post the full error?

**Comment by weilah** [comment]
Hey, sorry for the late response and thanks for getting back to me. I'll try to give you as much hints as possible.

I'm running the Maloja version 3.1.5 on Docker.
This is how my settings.ini looks like:
```
[MALOJA]
lastfm_api_key = False
spotify_api_id = xxxxxxxxxxxxxxx
spotify_api_secret = xxxxxxxxxxxxx
audiodb_api_key = False
default_range_charts_artists = month
default_range_charts_tracks = month
invalid_artists = {'Die Kita-Frösche', 'Simone Sommerland', 'Karsten Glück'}
```


After editing the settings.ini I stop and start the container and everything works fine. But as soon as I scrobble a song matching the invalid artist I get the following when reloading Maloja site:

![image](https://github.com/krateng/maloja/assets/16925690/d1956788-ee02-4a1a-b13f-3dad9491a73e)


This is what I can see in the logs of the running container (I'll try to get only the relevant data, please let me know if I missed something):

```
[database] Incoming scrobble [Client: multi-scrobbler | API: native/v1]: {'track_artists': ['Simone Sommerland', 'Karsten Glück', 'Die Kita-Frösche'], 'track_title': 'Aramsamsam', 'album_name': 'Die 30 besten Spiel- und Bewegungslieder', 'track_length': 93, 'scrobble_time': 1698048057}
[dbcache] Invalidated 176 of 2146 DB cache entries
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 47, in outer_func
    return cache[key]
KeyError: ('[]', '{"since": 1698019200, "to": 1698105599}', <function connection_provider.<locals>.wrapper at 0x7f8d6b9fea60>, 1698019200, 1698105599)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 240, in mainpage
    return jinja_page("start")
  File "/usr/lib/python3.9/site-packages/maloja/dev/profiler.py", line 27, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 218, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 1, in top-level template code
    {% extends "abstracts/base.jinja" %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/abstracts/base.jinja", line 34, in top-level template code
    {% block content %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/start.jinja", line 58, in block 'content'
    {% include 'partials/charts_tracks_tiles.jinja' %}
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/partials/charts_tracks_tiles.jinja", line 5, in top-level template code
    {% set charts = dbc.get_charts_tracks(filterkeys,limitkeys) %}
  File "/usr/lib/python3.9/site-packages/maloja/database/jinjaview.py", line 47, in packedmethod
    result = originalmethod(**kwargs,dbconn=self.conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 52, in newfunc
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 263, in get_charts_tracks
    result = sqldb.count_scrobbles_by_track(since=since,to=to,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 49, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 115, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 683, in count_scrobbles_by_track
    tracks = get_tracks_map([row.track_id for row in result],dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 74, in outer_func
    remaining = inner_func(set(e for e in set_arg if e not in result),dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 115, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 749, in get_tracks_map
    trackdicts = tracks_db_to_dict(result,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 188, in tracks_db_to_dict
    return [
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 190, in <listcomp>
    "artists":artists[row.id],
KeyError: 7658
```

as you can see, I'm using multi-scrobbler to get my scrobbles from Last.fm. It might be worth mentioning that until now I was deleting the unwanted scrobbles manually through the build-in functionality when logged in as admin with _Admin Mode_ enabled. Not sure if this could be related.

I can post more info if needed.

**Comment by weilah** [comment]
as soon as I remove the invalid_artists line from the settings.ini and restart the container everything seems to be working normal again. The unwanted track was not scrobbled though ¯\_(ツ)_/¯

this is the container's log right after removing the line in settings.ini and restarting it:
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 47, in outer_func
    return cache[key]
KeyError: ('[]', '{}', <function connection_provider.<locals>.wrapper at 0x7f0e52d09e50>, None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 476, in start_db
    firstscrobble = sqldb.get_scrobbles()[0]
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 49, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 120, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 561, in get_scrobbles
    result = scrobbles_db_to_dict(result,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 165, in scrobbles_db_to_dict
    tracks = get_tracks_map(set(row.track_id for row in rows),dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 74, in outer_func
    remaining = inner_func(set(e for e in set_arg if e not in result),dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 115, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 749, in get_tracks_map
    trackdicts = tracks_db_to_dict(result,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 188, in tracks_db_to_dict
    return [
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 190, in <listcomp>
    "artists":artists[row.id],
KeyError: 7658
[dbcache] Cache: Size: 0 | Hits: 0/1 | Estimated Memory: 72 B
[sqldb] Database Cleanup...
[dbcache] Entity Cache: Size: 7635 | Hits: 0/15272 | Estimated Memory: 1 MiB
[dbcache] System RAM Utilization: 47.4%
[sqldb] Deleting (1698048057, '{"track_artists": ["Simone Sommerland", "Karsten Gl\\u00fcck", "Die Kita-Fr\\u00f6sche"], "track_title": "Aramsamsam", "album_name": "Die 30 besten Spiel- und Bewegungslieder", "track_length": 93, "scrobble_time": 1698048057}', 'client:multi-scrobbler', None, 7658, None)
[sqldb] Deleting (7658, 'Aramsamsam', 'aramsamsam', 93)
[sqldb] Database Cleanup complete!
```

**Comment by weilah** [comment]
Hey @krateng I have seen you have been busy working on the 'Nicole' version. Congrats on that, I'll pull it right away. Doesn't look like there is anything related to the invalid artist feature but nonetheless I'll try again after deploying the new version.

**Comment by krateng** [comment]
Should be fixed in the next patch!

**Comment by weilah** [comment]
Excellent! thanks :)

PS: I was looking in your profile for some "buy me a coffee" thing, but wasn't able to find one

**Comment by weilah** [comment]
Hi @krateng,
not sure if I should open a new issue since is directly related with what I firstly reported here. Please let me know if I should create a new one.

After the latest update (Version 3.2.1) the invalid_artist setting does indeed work and the unwanted artist don't get scrobbled and Maloja 

But now I'm seeing the following logs in Multi Scrobbler which leaves it forever trying:
```
2023-11-18T23:45:40+01:00 info    : [Scrobblers] [Maloja - unnamed-mlj] Scrobble processing retries (1) less than max processing retries (5), restarting processing after 7 second delay...
2023-11-18T23:45:40+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Error occurred while trying to scrobble
ErrorWithCause: 
    at f.doProcessing (CWD/build/server.js:1:42919)
    at async f.startScrobbling (CWD/build/server.js:1:39715)
    at async f.initScrobbleMonitoring (CWD/build/server.js:1:39243)

caused by: Error: Bad Request
    at Request.callback (CWD/node_modules/superagent/lib/node/index.js:845:17)
    at CWD/node_modules/superagent/lib/node/index.js:1070:18
    at IncomingMessage.<anonymous> (CWD/node_modules/superagent/lib/node/parsers/json.js:21:7)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-11-18T23:45:40+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Scrobble processing interrupted
2023-11-18T23:45:40+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Scrobble Error (New) {"payload":{"album":"Die 30 besten Spiel- und Bewegungslieder","artists":["Simone Sommerland","Karsten Glück","Die Kita-Frösche"],"duration":163.16,"key":"1YD02CsVgfTwLpURMYBaKHnswVLFOQUKzrD3xqRzL6Zbc7Nv1lLcZSce0eoWVl","length":187.28,"time":1700347278,"title":"Die Maus auf Weltraumreise"},"playInfo":"Simone Sommerland / Karsten Glück / Die Kita-Frösche - Die Maus auf Weltraumreise @ 2023-11-18T23:41:18+01:00"}
2023-11-18T23:45:40+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] API Call failed: Server Response => Bad Request {"response":{"error":{"desc":"The scrobble is missing needed parameters.","type":"missing_scrobble_data","value":"artist"},"status":"failure"},"status":400}
2023-11-18T23:45:39+01:00 warn    : [Scrobblers] [Maloja - unnamed-mlj] Request failed but retries (0) less than max (1), retrying request after 1.5 seconds...
2023-11-18T23:45:39+01:00 info    : [Scrobblers] [Maloja - unnamed-mlj] Scrobble processing started
2023-11-18T23:45:35+01:00 info    : [Scrobblers] [Maloja - unnamed-mlj] Scrobble processing retries (0) less than max processing retries (5), restarting processing after 4 second delay...
2023-11-18T23:45:35+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Error occurred while trying to scrobble
ErrorWithCause: 
    at f.doProcessing (CWD/build/server.js:1:42919)
    at async f.startScrobbling (CWD/build/server.js:1:39715)
    at async f.initScrobbleMonitoring (CWD/build/server.js:1:39243)

caused by: Error: Bad Request
    at Request.callback (CWD/node_modules/superagent/lib/node/index.js:845:17)
    at CWD/node_modules/superagent/lib/node/index.js:1070:18
    at IncomingMessage.<anonymous> (CWD/node_modules/superagent/lib/node/parsers/json.js:21:7)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-11-18T23:45:35+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Scrobble processing interrupted
2023-11-18T23:45:35+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] Scrobble Error (New) {"payload":{"album":"Die 30 besten Spiel- und Bewegungslieder","artists":["Simone Sommerland","Karsten Glück","Die Kita-Frösche"],"duration":163.16,"key":"1YD02CsVgfTwLpURMYBaKHnswVLFOQUKzrD3xqRzL6Zbc7Nv1lLcZSce0eoWVl","length":187.28,"time":1700347278,"title":"Die Maus auf Weltraumreise"},"playInfo":"Simone Sommerland / Karsten Glück / Die Kita-Frösche - Die Maus auf Weltraumreise @ 2023-11-18T23:41:18+01:00"}
2023-11-18T23:45:35+01:00 error   : [Scrobblers] [Maloja - unnamed-mlj] API Call failed: Server Response => Bad Request {"response":{"error":{"desc":"The scrobble is missing needed parameters.","type":"missing_scrobble_data","value":"artist"},"status":"failure"},"status":400}
2023-11-18T23:45:33+01:00 warn    : [Scrobblers] [Maloja - unnamed-mlj] Request failed but retries (0) less than max (1), retrying request after 1.5 seconds...
2023-11-18T23:45:32+01:00 info    : [Sources] [Spotify - unnamed] Discovered => Simone Sommerland / Karsten Glück / Die Kita-Frösche - Die Maus auf Weltraumreise @ 2023-11-18T23:41:18+01:00
```

Again, please let me know if I can provide you with more needed info.
Thanks!
