### ISSUE TITLE
Reject empty password.

### ISSUE THREAD

**Issue by kirinokirino** [krateng/maloja#255]
after inputting nothing in the password field in  `/admin_overview` got this traceback in the console: 
`Traceback (most recent call last):
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/bin/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/lib/python3.11/site-packages/nimrodel/_api.py", line 160, in route
    result = self.handle(nodes,reqmethod,keys,headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/lib/python3.11/site-packages/nimrodel/_apifunction.py", line 79, in handle
    return func(**querykeys,**pathkeys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/lib/python3.11/site-packages/doreah/auth.py", line 172, in get_token
    if u.validate_challenge(challenge,response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/lib/python3.11/site-packages/doreah/auth.py", line 109, in validate_challenge
    if combine(pub,challenge) == combine(response,COMMON):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kirinokirino/Documents/Sources/maloja/.venv/lib/python3.11/site-packages/doreah/auth.py", line 74, in combine
    a = int(a,16)`

**Comment by BitesizedLion** [comment]
Looks like this has been fixed? Can't reproduce on 3.2.2
