### ISSUE TITLE
No API Secrets results in TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Sohalt** [krateng/maloja#26]
When I don't specify any API secrets I get the following error:
```
Various external services can be used to display images. If not enough of them are set up, only local images will be used.
	Currently not using a Last.fm API Key for image display.
	Currently not using a Fanart.tv API Key for image display.
	Currently not using a Spotify Client ID for image display.
	Currently not using a Spotify Client Secret for image display.
Traceback (most recent call last):
  File "/tmp/env/bin/maloja", line 10, in <module>
    sys.exit(main())
  File "/tmp/env/lib/python3.7/site-packages/doreah/control.py", line 44, in wrapper
    return func(*args,**kwargs)
  File "/tmp/env/lib/python3.7/site-packages/maloja/proccontrol/control.py", line 91, in main
    if action in actions: actions[action](*args,**kwargs)
  File "/tmp/env/lib/python3.7/site-packages/maloja/proccontrol/control.py", line 73, in direct
    from .. import server
  File "/tmp/env/lib/python3.7/site-packages/maloja/server.py", line 14, in <module>
    from . import database
  File "/tmp/env/lib/python3.7/site-packages/maloja/database.py", line 5, in <module>
    from .cleanup import CleanerAgent, CollectorAgent
  File "/tmp/env/lib/python3.7/site-packages/maloja/cleanup.py", line 2, in <module>
    from . import utilities
  File "/tmp/env/lib/python3.7/site-packages/maloja/utilities.py", line 18, in <module>
    from . import thirdparty
  File "/tmp/env/lib/python3.7/site-packages/maloja/thirdparty/__init__.py", line 202, in <module>
    from . import *
  File "/tmp/env/lib/python3.7/site-packages/maloja/thirdparty/spotify.py", line 6, in <module>
    class Spotify(MetadataInterface):
  File "/tmp/env/lib/python3.7/site-packages/maloja/thirdparty/__init__.py", line 71, in __init_subclass__
    s = cls()
  File "/tmp/env/lib/python3.7/site-packages/maloja/thirdparty/__init__.py", line 67, in __init__
    self.authorize()
  File "/tmp/env/lib/python3.7/site-packages/maloja/thirdparty/spotify.py", line 31, in authorize
    "Authorization":"Basic " + b64(utf(self.settings["apiid"] + ":" + self.settings["secret"])).decode("utf-8")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by krateng** [comment]
Ah, oversight in the refactoring, should be fixed with the next version!
