### ISSUE TITLE
500 internal server error when trying to view top albums

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#262]
After running `maloja parsealbums` and restarting I can see top albums on the main dashboard but navigating to `/charts_albums`, regarless of time period set, produces a 500 error.

```
[debug_performance] Executed jinja_page (('album',), {}) in 2.663s (Average: 5.529s)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/lib/python3.10/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.10/site-packages/maloja/server.py", line 231, in jinja_page_public
    return jinja_page(name)
  File "/usr/lib/python3.10/site-packages/maloja/dev/profiler.py", line 42, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.10/site-packages/maloja/server.py", line 214, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/charts_albums.jinja", line 17, in top-level template code
    {% set img = "/favicon.png" %}
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/abstracts/base.jinja", line 45, in top-level template code
    {% block content %}
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/charts_albums.jinja", line 46, in block 'content'
    {% include 'partials/charts_albums.jinja' %}
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/partials/charts_albums.jinja", line 49, in top-level template code
    {{ entityrow.row(e['album'],adminmode=adminmode) }}
  File "/usr/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/snippets/entityrow.jinja", line 20, in template
    <td class='searchProvider'>{{ links.link_search(entity) }}</td>
  File "/usr/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/lib/python3.10/site-packages/maloja/web/jinja/snippets/links.jinja", line 71, in template
    {% set searchstr = (entity.artists + [entity.title]) | join(" ") | urlencode %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

Version 3.2.0
Docker `krateng/maloja:latest`

**Comment by krateng** [comment]
Should be fixed in the next patch!
