### ISSUE TITLE
Not starting without Spotify API ID

### ISSUE THREAD

**Issue by phw** [krateng/maloja#273]
Without setting a Spotify API ID the server crashes on startup. Running with docker without or with empty `MALOJA_SPOTIF_API_ID` results in:

```
Attaching to maloja-maloja-1
maloja-maloja-1  | [migrations] started
maloja-maloja-1  | [migrations] no migrations found
maloja-maloja-1  | ───────────────────────────────────────
maloja-maloja-1  |   _____ __ __ _____ _____ _____ _____ 
maloja-maloja-1  |  |     |  |  |   __|_   _|     |     |
maloja-maloja-1  |  |   --|  |  |__   | | | |  |  | | | |
maloja-maloja-1  |  |_____|_____|_____| |_| |_____|_|_|_|
maloja-maloja-1  |        _____ __ __ _ __    ____  
maloja-maloja-1  |       | __  |  |  | |  |  |    \ 
maloja-maloja-1  |       | __ -|  |  | |  |__|  |  |
maloja-maloja-1  |       |_____|_____|_|_____|____/ 
maloja-maloja-1  | 
maloja-maloja-1  |   Based on images from linuxserver.io
maloja-maloja-1  | ───────────────────────────────────────
maloja-maloja-1  | 
maloja-maloja-1  | To support LSIO projects visit:
maloja-maloja-1  | https://www.linuxserver.io/donate/
maloja-maloja-1  | 
maloja-maloja-1  | ───────────────────────────────────────
maloja-maloja-1  | GID/UID
maloja-maloja-1  | ───────────────────────────────────────
maloja-maloja-1  | 
maloja-maloja-1  | User UID:    0
maloja-maloja-1  | User GID:    0
maloja-maloja-1  | ───────────────────────────────────────
maloja-maloja-1  | 
maloja-maloja-1  | -------------------------------------
maloja-maloja-1  | WARN: Running as root! If you meant to do this than this message can be ignored.
maloja-maloja-1  | If you are running this container on a *linux* host and are not using podman rootless you SHOULD
maloja-maloja-1  | change the ENVs PUID and PGID for this container to ensure correct permissions on your config folder.
maloja-maloja-1  | See: https://github.com/krateng/maloja#linux-host
maloja-maloja-1  | 
maloja-maloja-1  | -------------------------------------
maloja-maloja-1  | 
maloja-maloja-1  | [custom-init] No custom files found, skipping...
maloja-maloja-1  | 
maloja-maloja-1  | Maloja is starting!
maloja-maloja-1  | [ls.io-init] done.
maloja-maloja-1  | 
maloja-maloja-1  | Maloja v3.2.0
maloja-maloja-1  | https://github.com/krateng/maloja
maloja-maloja-1  | 
maloja-maloja-1  | Various external services can be used to display images. If not enough of them are set up, only local images will be used.
maloja-maloja-1  | 	Last.fm API Key found.
maloja-maloja-1  | 	Please enter your Spotify API ID. If you do not want to use one at this moment, simply leave this empty and press Enter.
maloja-maloja-1  | Traceback (most recent call last):
maloja-maloja-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
maloja-maloja-1  |     return _run_code(code, main_globals, None,
maloja-maloja-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
maloja-maloja-1  |     exec(code, run_globals)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 153, in <module>
maloja-maloja-1  |     def main(*args,**kwargs):
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/control.py", line 57, in decorator
maloja-maloja-1  |     wrapper()
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/control.py", line 51, in wrapper
maloja-maloja-1  |     result = func(*args,**kwargs)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 186, in main
maloja-maloja-1  |     return action(*args,**kwargs)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 107, in run_server
maloja-maloja-1  |     setup()
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/setup.py", line 48, in setup
maloja-maloja-1  |     key = prompt(promptmsg,types=(str,),default=False,skip=SKIP)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/io.py", line 65, in prompt
maloja-maloja-1  |     inp = getpass("") if secret else input()
maloja-maloja-1  | EOFError: EOF when reading a line
maloja-maloja-1  | 
maloja-maloja-1  | Maloja is starting!
maloja-maloja-1  | 
maloja-maloja-1  | Maloja v3.2.0
maloja-maloja-1  | https://github.com/krateng/maloja
maloja-maloja-1  | 
maloja-maloja-1  | Various external services can be used to display images. If not enough of them are set up, only local images will be used.
maloja-maloja-1  | 	Last.fm API Key found.
maloja-maloja-1  | 	Please enter your Spotify API ID. If you do not want to use one at this moment, simply leave this empty and press Enter.
maloja-maloja-1  | Traceback (most recent call last):
maloja-maloja-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
maloja-maloja-1  |     return _run_code(code, main_globals, None,
maloja-maloja-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
maloja-maloja-1  |     exec(code, run_globals)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 153, in <module>
maloja-maloja-1  |     def main(*args,**kwargs):
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/control.py", line 57, in decorator
maloja-maloja-1  |     wrapper()
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/control.py", line 51, in wrapper
maloja-maloja-1  |     result = func(*args,**kwargs)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 186, in main
maloja-maloja-1  |     return action(*args,**kwargs)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/__main__.py", line 107, in run_server
maloja-maloja-1  |     setup()
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/maloja/setup.py", line 48, in setup
maloja-maloja-1  |     key = prompt(promptmsg,types=(str,),default=False,skip=SKIP)
maloja-maloja-1  |   File "/usr/lib/python3.10/site-packages/doreah/io.py", line 65, in prompt
maloja-maloja-1  |     inp = getpass("") if secret else input()
maloja-maloja-1  | EOFError: EOF when reading a line
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
```

`MALOJA_SKIP_SETUP=1`  is set. Setting `MALOJA_SPOTIF_API_ID` to any non-empty value allows the server to start.

IMHO it should be possible to not use Spotify at all. At least if `MALOJA_SKIP_SETUP` is set it should not attempt to read data from input.

I also tried setting `MALOJA_METADATA_PROVIDERS=lastfm,deezer,audiodb,musicbrainz`  (without Spotify) in the hope this would skip the spotify setup, but it still tries to read the spotify API ID on startup.

**Comment by krateng** [comment]
`MALOJA_SKIP_SETUP` should be set to 'yes' or 'true', it doesn't actually work with 1. The containerfile takes care of that, so you don't need to set it yourself. The EOFError is simply a consequence of running inside a container without SKIP_SETUP enabled, I can probably add some output for that.

**Comment by phw** [comment]
Got it, I'll try that and report back

**Comment by phw** [comment]
Yes, not setting that variable at all or setting it to "yes" works as expected
