### ISSUE TITLE
Update from 2.6.4 to 2.7.8 appears to break database maintenance

### ISSUE THREAD

**Issue by ICTman1076** [krateng/maloja#29]
URL Affected: [maloja instance]/admin_issues

Page returned: 500

maloja debug output:

```
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/maloja/.local/lib/python3.7/site-packages/doreah/auth.py", line 197, in newfunc
    return func(*args,**kwargs)
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/server.py", line 232, in static_html_private
    return static_html(name)
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/server.py", line 263, in static_html
    res = template.render(**LOCAL_CONTEXT)
  File "/home/maloja/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/maloja/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/maloja/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/web/jinja/admin_issues.jinja", line 35, in top-level template code
    {% set issuedata = dbp.issues() %}
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/web/jinja/abstracts/admin.jinja", line 1, in top-level template code
    {% extends "abstracts/base.jinja" %}
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/web/jinja/abstracts/base.jinja", line 21, in top-level template code
    {% block content %}
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/web/jinja/abstracts/admin.jinja", line 47, in block "content"
    {% block maincontent %}
  File "/home/maloja/.local/lib/python3.7/site-packages/maloja/web/jinja/admin_issues.jinja", line 61, in block "maincontent"
    <td>{{ artistLink(issue[0]) }} sounds like the combination of {{ len(issue[1]) }} artists:
jinja2.exceptions.UndefinedError: 'artistLink' is undefined
```

I'll leave my Maloja database as it is (save for scrobbling new tracks) if you need it for debugging

**Comment by krateng** [comment]
Ah, looks like another careless oversight by me :D
Should work in 2.7.9!

**Comment by ICTman1076** [comment]
Awesome, thanks :)

On 27 August 2020 14:55:36 BST, krateng <notifications@github.com> wrote:
>Ah, looks like another careless oversight by me :D
>Should work in 2.7.9!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/krateng/maloja/issues/29#issuecomment-681964386
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
