### ISSUE TITLE
v3.2.2: PermissionError: Directory /home/stuff/maloja/maloja-data/auth is not usable!

### ISSUE THREAD

**Issue by jan666** [krateng/maloja#313]
I updated to v3.2.2 and now maloja won't start:

```
[...]
Building wheels for collected packages: malojaserver
  Building wheel for malojaserver (pyproject.toml) ... done
  Created wheel for malojaserver: filename=malojaserver-3.2.2-py3-none-any.whl size=1515435 sha256=fe42be925406cd115b4a2b5a9c9410dccc2f3a3ccf716b5c4670ac4f07b69df7
  Stored in directory: /tmp/pip-ephem-wheel-cache-vgvmacar/wheels/08/40/d5/ec83db49ab275c57b8f3e1e8db152591760a6804d21e77102c
Successfully built malojaserver
Installing collected packages: malojaserver
  Attempting uninstall: malojaserver
    Found existing installation: malojaserver 3.2.1
    Uninstalling malojaserver-3.2.1:
      Successfully uninstalled malojaserver-3.2.1
Successfully installed malojaserver-3.2.2
(py311env-maloja) stuff@python:~/git/maloja % maloja start
Directory /home/stuff/maloja/maloja-data/auth is not usable.
Please change permissions or settings!
Traceback (most recent call last):
  File "/home/stuff/maloja/py311env-maloja/bin/maloja", line 5, in <module>
    from maloja.__main__ import main
  File "/home/stuff/maloja/py311env-maloja/lib/python3.11/site-packages/maloja/__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "/home/stuff/maloja/py311env-maloja/lib/python3.11/site-packages/maloja/pkg_global/conf.py", line 315, in <module>
    if not is_dir_usable(path): raise PermissionError(f"Directory {path} is not usable!")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: Directory /home/stuff/maloja/maloja-data/auth is not usable!
```

I think it sould be the correct permission...?

```
(py311env-maloja) stuff@python:~/git/maloja % ls -lah /home/stuff/maloja/maloja-data/auth/
total 22
drwxr-xr-x   2 stuff  stuff     4B Dec 18 13:00 .
drwxr-xr-x  11 stuff  stuff    18B Dec 18 13:03 ..
-rw-r--r--   1 stuff  stuff   7.3K Dec 18 13:00 auth.ddb
-rw-r--r--   1 stuff  stuff     0B Mar  3  2023 dummy
```

Going back to v3.2.1 just works again:

```
[...]
Building wheels for collected packages: malojaserver
  Building wheel for malojaserver (pyproject.toml) ... done
  Created wheel for malojaserver: filename=malojaserver-3.2.1-py3-none-any.whl size=1514509 sha256=47d9fb2fc0965e9e01fb3b6c5954f66b203697b9955a1a0eefb24d8f185d78ca
  Stored in directory: /tmp/pip-ephem-wheel-cache-1hulqoro/wheels/08/40/d5/ec83db49ab275c57b8f3e1e8db152591760a6804d21e77102c
Successfully built malojaserver
Installing collected packages: malojaserver
  Attempting uninstall: malojaserver
    Found existing installation: malojaserver 3.2.2
    Uninstalling malojaserver-3.2.2:
      Successfully uninstalled malojaserver-3.2.2
Successfully installed malojaserver-3.2.1
(py311env-maloja) stuff@python:~/git/maloja % maloja start
[lastfm] Error while authenticating with LastFM: AttributeError("'NoneType' object has no attribute 'encode'")

Maloja v3.2.1
https://github.com/krateng/maloja
```

**Comment by krateng** [comment]
Do you have write permissions to the directory as the user that runs maloja?

**Comment by jan666** [comment]
> Is maloja running as the user stuff?

yes

> Can you try replacing Line 36 with `raise` in `~/git/maloja/maloja/pkg_global/conf.py` and run it again?

```
(py311env-maloja) stuff@python:~/git/maloja % git diff
diff --git a/maloja/pkg_global/conf.py b/maloja/pkg_global/conf.py
index 26ff692..850dbec 100644
--- a/maloja/pkg_global/conf.py
+++ b/maloja/pkg_global/conf.py
@@ -33,7 +33,7 @@ def is_dir_usable(pth):
                os.remove(pthj(pth,".test"))
                return True
        except Exception:
-               return False
+               raise

 def get_env_vars(key,pathsuffix=[]):
        return [pthj(pth,*pathsuffix) for pth in os.environ.get(key,'').split(':') if pth != '']
```

no success:

```
(py311env-maloja) stuff@python:~/git/maloja % pip install .
[...]
Building wheels for collected packages: malojaserver
  Building wheel for malojaserver (pyproject.toml) ... done
  Created wheel for malojaserver: filename=malojaserver-3.2.2-py3-none-any.whl size=1515433 sha256=a08c22021a3ef940d11a7043da87e3abd14809e3f1a08c595809cf00157213a7
  Stored in directory: /tmp/pip-ephem-wheel-cache-01gt82l0/wheels/08/40/d5/ec83db49ab275c57b8f3e1e8db152591760a6804d21e77102c
Successfully built malojaserver
Installing collected packages: malojaserver
  Attempting uninstall: malojaserver
    Found existing installation: malojaserver 3.2.1
    Uninstalling malojaserver-3.2.1:
      Successfully uninstalled malojaserver-3.2.1
Successfully installed malojaserver-3.2.2
(py311env-maloja) stuff@python:~/git/maloja % maloja start
Traceback (most recent call last):
  File "/home/stuff/maloja/py311env-maloja/bin/maloja", line 5, in <module>
    from maloja.__main__ import main
  File "/home/stuff/maloja/py311env-maloja/lib/python3.11/site-packages/maloja/__init__.py", line 4, in <module>
    from .pkg_global import conf
  File "/home/stuff/maloja/py311env-maloja/lib/python3.11/site-packages/maloja/pkg_global/conf.py", line 315, in <module>
    if not is_dir_usable(path): raise PermissionError(f"Directory {path} is not usable!")
           ^^^^^^^^^^^^^^^^^^^
  File "/home/stuff/maloja/py311env-maloja/lib/python3.11/site-packages/maloja/pkg_global/conf.py", line 32, in is_dir_usable
    os.mknod(pthj(pth,".test"))
OSError: [Errno 22] Invalid argument
```

**Comment by krateng** [comment]
Alright not sure why this would cause an invalid argument error, but I changed it - can you try from source?

**Comment by jan666** [comment]
Works when building from master: Currently installed Maloja version: 3.2.2

**Comment by nothing2obvi** [comment]
I was using `3.2.2` for a while but suddenly today it started giving the same error as OP. I downgraded to `3.2.1` and it works just fine now.

I didn't want to build from source because I wanted Maloja in a Docker container.
