### ISSUE TITLE
Occasional database timeout

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#340]
Running docker image built off of https://github.com/duckfromdiscord/maloja/tree/as2.0-xml (API XML fix)
Every so often a singular request takes a long time and then errors with:
```py
<h1>Critical error while processing request: /track</h1>
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
           ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/maloja/server.py", line 235, in mainpage
    return jinja_page("start")
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/maloja/dev/profiler.py", line 41, in newfunc
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/maloja/server.py", line 199, in jinja_page
    adminmode = request.cookies.get("adminmode") == "true" and auth.check_request(request)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/doreah/auth.py", line 171, in check_request
    if user := self.check_session(token):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/doreah/auth.py", line 161, in check_session
    session = dbsess.query(Session).where(Session.session_token==token).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2727, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2826, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 157, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
```

**Comment by marvinscham** [comment]
Had the same issue, seems to be related to the auth implementation provided by doreah.

https://github.com/krateng/maloja/blob/3ba27ffc371d6087b58314231d9bc291a0d163c2/maloja/pkg_global/conf.py#L348

I replaced the code above with the following monkey patch to temporarily alleviate the issue.

```python
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

auth = doreah.auth.AuthManager(
    singleuser=True,
    cookieprefix='maloja',
    stylesheets=("/maloja.css",),
    dbfile=data_dir['auth']("auth.sqlite")
)

# Kill old engine and patch it
auth.engine.dispose()
auth.engine = create_engine(
    f"sqlite:///{auth.dbfile}",
    echo=False,
    connect_args={"check_same_thread": False},
    poolclass=NullPool
)

# Rebind session factory to patched engine
from sqlalchemy.orm import sessionmaker, scoped_session
session_factory = sessionmaker(bind=auth.engine)
auth.ScopedSession = scoped_session(session_factory)
```
