### ISSUE TITLE
Unable to import last.fm scrobbles

### ISSUE THREAD

**Issue by ducky710** [krateng/maloja#74]
Hello, whenever I attempt to run the maloja import command the following occurs. No matter how large the .csv file is. I attempted it with even a file that had only ten lines and got the same result. I used the recommend web tool to export my last.fm scrobbles.

`Already imported Last.FM data. Overwrite? [y/N]
y
Please wait...
Traceback (most recent call last):
  File "/usr/local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/doreah/control.py", line 47, in wrapper
    return func(*args,**kwargs)
  File "/usr/local/lib/python3.9/site-packages/maloja/proccontrol/control.py", line 91, in main
    if action in actions: actions[action](*args,**kwargs)
  File "/usr/local/lib/python3.9/site-packages/maloja/proccontrol/tasks/__init__.py", line 20, in loadlastfm
    convert(filename,data_dir['scrobbles']("lastfmimport.tsv"))
  File "/usr/local/lib/python3.9/site-packages/maloja/proccontrol/tasks/lastfmconverter.py", line 25, in convert
    album = data[1]
IndexError: list index out of range`

**Maloja Debug output**

`Various external services can be used to display images. If not enough of them are set up, only local images will be used.
        Last.fm API Key found.
        Fanart.tv API Key found.
        Spotify Client ID found.
        Spotify Client Secret found.
[thirdparty] LastFM registered as metadata provider
[thirdparty] Spotify registered as metadata provider
[thirdparty] MusicBrainz registered as metadata provider
[database] Starting database...
[database] Building database...
[database] Found 8 scrobbles...
Loading scrobbles |████████████----------------------------------------------------------------------------------------| 12%
Loading scrobbles |█████████████████████████---------------------------------------------------------------------------| 25%
Loading scrobbles |█████████████████████████████████████---------------------------------------------------------------| 38%
Loading scrobbles |██████████████████████████████████████████████████--------------------------------------------------| 50%
Loading scrobbles |██████████████████████████████████████████████████████████████--------------------------------------| 62%
Loading scrobbles |███████████████████████████████████████████████████████████████████████████-------------------------| 75%
Loading scrobbles |███████████████████████████████████████████████████████████████████████████████████████-------------| 88%
Loading scrobbles |████████████████████████████████████████████████████████████████████████████████████████████████████| 100%

[database] Database loaded, optimizing...
[database] Database fully built!
[maintenance] Sending daily stats report...
[database] Authenticated Machines: , ,
[database] Database reachable!
[server] Starting up Maloja server...
Traceback (most recent call last):
  File "/usr/local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/doreah/control.py", line 47, in wrapper
    return func(*args,**kwargs)
  File "/usr/local/lib/python3.9/site-packages/maloja/proccontrol/control.py", line 91, in main
    if action in actions: actions[action](*args,**kwargs)
  File "/usr/local/lib/python3.9/site-packages/maloja/proccontrol/control.py", line 73, in direct
    from .. import server
  File "/usr/local/lib/python3.9/site-packages/maloja/server.py", line 277, in <module>
    waitress.serve(webserver, host=HOST, port=MAIN_PORT, threads=THREADS)
  File "/usr/local/lib/python3.9/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.9/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/usr/local/lib/python3.9/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.9/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.9/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address in use
[debug] Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
[debug] Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
[maintenance] Could not send daily report!`

**Comment by krateng** [comment]
Would you mind sharing the exact content of the (ten line) file you're trying this with?

**Comment by ducky710** [comment]
Sure. Here are both files just incase.
[test.csv](https://github.com/krateng/maloja/files/6532335/test.csv)
[beaute_citron.csv](https://github.com/krateng/maloja/files/6532336/beaute_citron.csv)

**Comment by krateng** [comment]
The files both work for me. I added some better feedback into 2.12.8, could you upgrade and post the console output again?

**Comment by ducky710** [comment]
Hey it works now. The output is much more verbose. Turns out the issue was "xbackbone" which i used to upload my file to and then wget it within the container was adding stuff into the .csv file. The update you made showed me that. Used the csv that i uploaded here to github and it worked perfectly. Thanks <3 
P.S I'm very happy that a fellow ONCE came up with such an awesome project <3

**Comment by krateng** [comment]
Glad to hear it! And TWICE ftw :D
