### ISSUE TITLE
TypeError: get_post_scrobble() missing 1 required positional argument: 'artist'

### ISSUE THREAD

**Issue by AngerburN** [krateng/maloja#75]
```
Traceback (most recent call last):
File "/usr/local/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/local/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/local/lib/python3.9/site-packages/nimrodel/_api.py", line 155, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/local/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/local/lib/python3.9/site-packages/doreah/auth.py", line 239, in newfunc
return func(*args,**kwargs)
TypeError: get_post_scrobble() missing 1 required positional argument: 'artist'
Traceback (most recent call last):
File "/usr/local/bin/bottle.py", line 868, in _handle
return route.call(**args)
File "/usr/local/bin/bottle.py", line 1748, in wrapper
rv = callback(*a, **ka)
File "/usr/local/lib/python3.9/site-packages/nimrodel/_api.py", line 155, in route
result = self.handle(nodes,reqmethod,keys,headers)
File "/usr/local/lib/python3.9/site-packages/nimrodel/_apifunction.py", line 79, in handle
return func(**querykeys,**pathkeys)
File "/usr/local/lib/python3.9/site-packages/doreah/auth.py", line 239, in newfunc
return func(*args,**kwargs)
TypeError: get_post_scrobble() missing 1 required positional argument: 'artist'
```

Getting this in the maloja logs on the unraid docker.

**Comment by krateng** [comment]
What scrobbler are you using?

**Comment by AngerburN** [comment]
airsonic-advanced looking in the logs there everything looks ok it scrobbles fine to Listenbrainz with the url specified.
yoururl.tld/apis/listenbrainz/1/submit-listens))

**Comment by krateng** [comment]
Hm, the traceback looks like it's somehow using the native API instead of the Listenbrainz one. Does the maloja api log show a message `Incoming scrobble (...)` before the error?

**Comment by AngerburN** [comment]
`2021-07-03 20:43:33.376 INFO --- o.a.p.s.s.ListenBrainzScrobbler : Successfully registered submission for song 'Savior In The Clockwork' at ListenBrainz (http://192.168.0.100:42010/api/s/listenbrainz/1/submit-listens): 2021-07-03T18:43:33.372110Z`

This is on airsonic.

```
2021/07/02 22:55:12  Incoming scrobble (): ARTISTS: ['Queen'], TRACK: Killer Queen
2021/07/02 22:55:53  Incoming scrobble (): ARTISTS: ['Queen'], TRACK: Killer Queen
2021/07/02 22:56:20  Incoming scrobble (): ARTISTS: ['AC/DC'], TRACK: TNT
2021/07/02 23:00:05  Query Cache: 1364 Perm Hits, 243 Tmp Hits, 244 Misses; Current Size: 176/25
2021/07/02 23:00:05  Aggregate Cache: 311 Perm Hits, 241 Tmp Hits, 172 Misses; Current Size: 88/18
2021/07/02 23:38:26  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/02 23:38:26  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/02 23:56:02  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/02 23:56:02  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/03 00:00:05  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/03 00:00:05  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2021/07/03 00:20:33  Query Cache: 0 Perm Hits, 5 Tmp Hits, 49 Misses; Current Size: 44/5
2021/07/03 00:20:33  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 10 Misses; Current Size: 0/10
2021/07/03 01:00:05  Query Cache: 44 Perm Hits, 10 Tmp Hits, 54 Misses; Current Size: 44/5
2021/07/03 01:00:05  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 20 Misses; Current Size: 0/10

That's in the debug.log file from maloja.
```

**Comment by krateng** [comment]
So does scrobbling work? Does your page show the scrobbles in the statistics?

**Comment by AngerburN** [comment]
Nope, when doing manual it works but from airsonic it does not.

**Comment by AngerburN** [comment]
Checking everything the url was way wrong. Whoever started the thread on the unraid docker gave the wrong url.
/api/s/listenbrainz/1/submit-listens this ons is wrong it should be /apis/listenbrainz/1/submit-listens. Fixed :)

**Comment by FoxxMD** [comment]
@AngerburN 
> Whoever started the thread on the unraid docker gave the wrong url.

That'd be me :flushed: 

I've now updated the thread to specify endpoint based on maloja version since the endpoint changed in >= v2.9
