### ISSUE TITLE
v2.12.13 docker image broke container

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#85]
My previously working docker container now crashes using the `latest` tag (`v2.12.13`) with this exception trace:

```
Traceback (most recent call last):
File "/usr/local/bin/maloja", line 5, in <module>
from maloja.proccontrol.control import main
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/control.py", line 8, in <module>
from .setup import setup
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/setup.py", line 5, in <module>
from doreah import auth
File "/usr/local/lib/python3.10/site-packages/doreah/auth.py", line 7, in <module>
from nimrodel import EAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/__init__.py", line 22, in <module>
from ._apiobject import API as ObjectAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/_apiobject.py", line 2, in <module>
from ._api import AbstractAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/_api.py", line 9, in <module>
from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
File "/usr/local/bin/maloja", line 5, in <module>
from maloja.proccontrol.control import main
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/control.py", line 8, in <module>
from .setup import setup
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/setup.py", line 5, in <module>
from doreah import auth
File "/usr/local/lib/python3.10/site-packages/doreah/auth.py", line 7, in <module>
from nimrodel import EAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/__init__.py", line 22, in <module>
from ._apiobject import API as ObjectAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/_apiobject.py", line 2, in <module>
from ._api import AbstractAPI
File "/usr/local/lib/python3.10/site-packages/nimrodel/_api.py", line 9, in <module>
from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

I can verify that rolling back to docker image `v2.12.10` works

**Comment by bpepple** [comment]
This bug isn't really with `maloja`, but a package that it's dependent on `nimrodel`. So, a bug should be opened here:

https://github.com/krateng/nimrodel/issues

The specific line that needs to fixed is this:

https://github.com/krateng/nimrodel/blob/fab5890db16c1c353d444383c5da101e8630c852/nimrodel/_api.py#L9

Shouldn't be an easy fix, tho obviously a new release of nimrodel would be needed to fix maloja.

**Comment by bpepple** [comment]
To fix it I believe you just need to change:

`from collections import Mapping`

to

`from collections.abc import Mapping`
